name: Label Check
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]
jobs:
  check_label:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'New Feature') &&
      !contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
      !contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
    runs-on: ubuntu-latest
    name: Check PR Type label is set
    steps:
      - name: "Failed to find proper PR Type label. Please add one of the following: 'New Feature', 'Enhancement', or 'Bug-Fix'"
        run: exit 1
